[global]
workgroup = smb
security = user
map to guest = never

[homes]
comment = Home Directories
browsable = no
read only = no
create mode = 0750

[bbssync]
valid users = bbssync
path = /etc/bbssync/www/bbssync/userdata/
public = no
writable = yes
comment = User Config Files
printable = no
guest ok = no
create mask = 0600
directory mask = 0700
